/* HN DESIGNER - PASO 9.1
   Selección estable de sectores + cajones restringidos al sector seleccionado.
   Proyecto independiente. No depende del HN Muebles real.
*/
let hnScene=null,hnCamera=null,hnRenderer=null,hnControls=null,hnAnimationId=null;
let hnRaycaster=new THREE.Raycaster(),hnMouse=new THREE.Vector2();
let hnDesignerInitialized=false,hnResizeBound=false,hnClickBound=false,timerDimensionesMaestras=null;
let hnModuloActual={moduleId:'mod_default',ancho:1000,alto:2000,profundidad:500,espesor:18,fondo:3,x:0,y:0,z:0};
let hnEspaciosActuales=[],hnSectoresActuales=[],hnElementosActuales=[],hnCajonesActuales=[],hnSeleccionActual=null;
const hnId=prefix=>prefix+'_'+Math.random().toString(36).slice(2,8);
const hnRound=n=>Math.round(Number(n)*10)/10;

function abrirHNDesigner(){const d=document.getElementById('hn-designer');if(!d)return;d.style.display='flex';initHNDesigner3D();if(hnRenderer)onHNDesignerResize();}
function cerrarHNDesigner(){const d=document.getElementById('hn-designer');if(d)d.style.display='none';if(hnAnimationId){cancelAnimationFrame(hnAnimationId);hnAnimationId=null;}}
function initHNDesigner3D(){
 const c=document.getElementById('hn-viewport-3d');if(!c)return;
 if(hnDesignerInitialized&&hnRenderer&&hnScene){onHNDesignerResize();if(!hnAnimationId)animateHNDesigner();return;}
 c.innerHTML='';const w=Math.max(c.clientWidth,1),h=Math.max(c.clientHeight,1);
 hnScene=new THREE.Scene();hnScene.background=new THREE.Color(0xf8fafc);
 hnCamera=new THREE.PerspectiveCamera(45,w/h,1,50000);hnCamera.position.set(0,1000,3000);
 hnRenderer=new THREE.WebGLRenderer({antialias:true});hnRenderer.setSize(w,h);hnRenderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));hnRenderer.shadowMap.enabled=true;c.appendChild(hnRenderer.domElement);
 hnControls=new THREE.OrbitControls(hnCamera,hnRenderer.domElement);hnControls.enableDamping=true;hnControls.dampingFactor=.05;hnControls.target.set(0,1000,0);
 hnScene.add(new THREE.AmbientLight(0xffffff,.7));const dl=new THREE.DirectionalLight(0xffffff,.6);dl.position.set(1000,3000,2000);hnScene.add(dl);const dl2=new THREE.DirectionalLight(0xffffff,.3);dl2.position.set(-1000,-1000,-2000);hnScene.add(dl2);
 const grid=new THREE.GridHelper(5000,50,0xd1d5db,0xe5e7eb);hnScene.add(grid);
 if(!hnClickBound){c.addEventListener('click',onHNDesignerClick,false);hnClickBound=true;}if(!hnResizeBound){window.addEventListener('resize',onHNDesignerResize,false);hnResizeBound=true;}
 hnDesignerInitialized=true;crearModuloNuevoParametrico();animateHNDesigner();
}
function animateHNDesigner(){if(document.getElementById('hn-designer')?.style.display==='none'){hnAnimationId=null;return;}hnAnimationId=requestAnimationFrame(animateHNDesigner);if(hnControls)hnControls.update();if(hnRenderer&&hnScene&&hnCamera)hnRenderer.render(hnScene,hnCamera);}
function onHNDesignerResize(){const c=document.getElementById('hn-viewport-3d');if(!c||!hnCamera||!hnRenderer)return;if(document.getElementById('hn-designer')?.style.display!=='flex')return;const w=Math.max(c.clientWidth,1),h=Math.max(c.clientHeight,1);hnCamera.aspect=w/h;hnCamera.updateProjectionMatrix();hnRenderer.setSize(w,h);}

function leerMaestras(){return{ancho:Math.max(100,parseFloat(document.getElementById('hn-master-ancho')?.value)||1000),alto:Math.max(100,parseFloat(document.getElementById('hn-master-alto')?.value)||2000),profundidad:Math.max(100,parseFloat(document.getElementById('hn-master-prof')?.value)||500),espesor:Math.max(3,parseFloat(document.getElementById('hn-master-espesor')?.value)||18),fondo:Math.max(1,parseFloat(document.getElementById('hn-master-fondo')?.value)||3)};}
function crearModuloNuevoParametrico(){const m=leerMaestras();Object.assign(hnModuloActual,m);hnEspaciosActuales=[{spaceId:hnId('space'),moduleId:hnModuloActual.moduleId,xMin:m.espesor,xMax:m.ancho-m.espesor,yMin:m.espesor,yMax:m.alto-m.espesor,profundidad:m.profundidad-m.fondo}];hnElementosActuales=[];hnCajonesActuales=[];hnSeleccionActual=null;recalcularSectores();reconstruirEscena3DParametrica();actualizarSidebarEspacios();restaurarPanelDerechoMaestro(false);}
function actualizarDimensionesMaestrasDebounced(){clearTimeout(timerDimensionesMaestras);timerDimensionesMaestras=setTimeout(ejecutarRecalculoParametricoCompleto,250);}
function ejecutarRecalculoParametricoCompleto(){const n=leerMaestras();const fx=n.ancho/hnModuloActual.ancho,fy=n.alto/hnModuloActual.alto;Object.assign(hnModuloActual,n);
 hnEspaciosActuales.forEach(e=>{e.xMin=Math.max(n.espesor,e.xMin*fx);e.xMax=Math.min(n.ancho-n.espesor,e.xMax*fx);e.yMin=n.espesor;e.yMax=n.alto-n.espesor;e.profundidad=n.profundidad-n.fondo;});
 hnElementosActuales.forEach(e=>{if(e.tipo==='montante'){e.x=Math.max(n.espesor+10,Math.min(e.x*fx,n.ancho-n.espesor-10));e.y=n.alto/2;e.alto=n.alto-2*n.espesor;e.profundidad=n.profundidad-n.fondo;}else if(e.tipo==='repisa'){const s=hnEspaciosActuales.find(x=>x.spaceId===e.spaceId);if(s){e.width=s.xMax-s.xMin;e.x=(s.xMin+s.xMax)/2;e.profundidad=s.profundidad;e.y=Math.max(s.yMin+n.espesor/2,Math.min(e.y,s.yMax-n.espesor/2));}}});
 recalcularEspaciosYElementosPorMontante();recalcularSectores();recalcularTodosLosCajones();reconstruirEscena3DParametrica();actualizarSidebarEspacios();}

function recalcularSectores(){
 const anteriores=hnSectoresActuales.slice();hnSectoresActuales=[];
 hnEspaciosActuales.forEach(space=>{const rep=hnElementosActuales.filter(e=>e.tipo==='repisa'&&e.spaceId===space.spaceId).sort((a,b)=>a.y-b.y);let limites=[space.yMin];rep.forEach(r=>{limites.push(r.y-r.espesor/2,r.y+r.espesor/2);});limites.push(space.yMax);
 let indice=0;for(let i=0;i+1<limites.length;i+=2){const y0=limites[i],y1=limites[i+1];if(y1-y0<=10)continue;const viejo=anteriores.find(s=>s.spaceId===space.spaceId&&Math.abs(s.yMin-y0)<4&&Math.abs(s.yMax-y1)<4);hnSectoresActuales.push({sectorId:viejo?.sectorId||`sec_${space.spaceId}_${indice}`,spaceId:space.spaceId,xMin:space.xMin,xMax:space.xMax,yMin:y0,yMax:y1,profundidad:space.profundidad});indice++;}}
 );
}
function limpiarParametricos(){const arr=[];hnScene.traverse(o=>{if(o.isMesh&&o.userData?.isParametric)arr.push(o);});arr.forEach(o=>{hnScene.remove(o);o.geometry?.dispose();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose();});}
function mat(color,transparent=false,opacity=1){return new THREE.MeshStandardMaterial({color,transparent,opacity,roughness:.4,metalness:.05,depthWrite:!transparent});}
function caja(data,color,ud){const g=new THREE.BoxGeometry(Math.max(1,data.width),Math.max(1,data.height),Math.max(1,data.depth));const m=mat(color);const mesh=new THREE.Mesh(g,m);mesh.position.set(data.x-hnModuloActual.ancho/2,data.y,data.z-hnModuloActual.profundidad/2);const ed=new THREE.LineSegments(new THREE.EdgesGeometry(g),new THREE.LineBasicMaterial({color:color===0xf59e0b?0xb45309:0x94a3b8}));mesh.add(ed);mesh.userData={isParametric:true,...ud};hnScene.add(mesh);return mesh;}
function reconstruirEscena3DParametrica(){if(!hnScene)return;limpiarParametricos();const W=hnModuloActual.ancho,H=hnModuloActual.alto,D=hnModuloActual.profundidad,T=hnModuloActual.espesor,F=hnModuloActual.fondo;
 [{width:T,height:H,depth:D,x:T/2,y:H/2,z:D/2},{width:T,height:H,depth:D,x:W-T/2,y:H/2,z:D/2},{width:W-2*T,height:T,depth:D,x:W/2,y:H-T/2,z:D/2},{width:W-2*T,height:T,depth:D,x:W/2,y:T/2,z:D/2},{width:W-2*T,height:H-2*T,depth:F,x:W/2,y:H/2,z:F/2}].forEach((p,i)=>caja(p,0xfafafa,{tipo:'estructura',estructura:true}));
 hnSectoresActuales.forEach(s=>{const sel=hnSeleccionActual?.tipo==='sector'&&hnSeleccionActual.objeto.sectorId===s.sectorId;const aw=s.xMax-s.xMin,ah=s.yMax-s.yMin,p=Math.max(20,s.profundidad-20);const g=new THREE.BoxGeometry(Math.max(8,aw-4),Math.max(8,ah-4),p);const mesh=new THREE.Mesh(g,mat(sel?0xf59e0b:0x3b82f6,true,sel?.32:.025));mesh.position.set(s.xMin+aw/2-W/2,s.yMin+ah/2,(p/2)-D/2);mesh.userData={isParametric:true,tipo:'sector',sectorData:s};if(sel)mesh.add(new THREE.LineSegments(new THREE.EdgesGeometry(g),new THREE.LineBasicMaterial({color:0xb45309})));hnScene.add(mesh);});
 hnElementosActuales.forEach(e=>{const sel=hnSeleccionActual?.objeto?.pieceId===e.pieceId;if(e.tipo==='montante')caja({width:e.espesor,height:e.alto,depth:e.profundidad,x:e.x,y:e.y,z:e.profundidad/2},sel?0xf59e0b:0xfafafa,{tipo:e.tipo,elementoData:e});else if(e.tipo==='repisa')caja({width:e.width,height:e.espesor,depth:e.profundidad,x:e.x,y:e.y,z:e.profundidad/2},sel?0xf59e0b:0xfafafa,{tipo:e.tipo,elementoData:e});});
 hnCajonesActuales.forEach(c=>c.piezas.forEach(p=>{const sel=hnSeleccionActual?.objeto?.pieceId===p.pieceId;const mesh=caja({width:p.ancho,height:p.alto,depth:p.profundidad,x:p.x,y:p.y,z:p.z},sel?0xf59e0b:0xfef3c7,{tipo:'cajon_pieza',elementoData:p,drawerId:c.drawerId,sectorId:c.sectorId,spaceId:c.spaceId});}));
 if(hnControls)hnControls.target.set(0,H/2,0);}

function agregarMontanteParametricoModal(){const x=hnModuloActual.ancho/2;if(x<=hnModuloActual.espesor+10)return;const id=hnId('mont');hnElementosActuales.push({pieceId:id,moduleId:hnModuloActual.moduleId,tipo:'montante',espesor:hnModuloActual.espesor,alto:hnModuloActual.alto-2*hnModuloActual.espesor,profundidad:hnModuloActual.profundidad-hnModuloActual.fondo,x,y:hnModuloActual.alto/2,z:(hnModuloActual.profundidad-hnModuloActual.fondo)/2,material:'Blanco'});recalcularEspaciosYElementosPorMontante();recalcularSectores();reconstruirEscena3DParametrica();actualizarSidebarEspacios();seleccionarElementoPorId(id);}
function recalcularEspaciosYElementosPorMontante(){const mont=hnElementosActuales.filter(e=>e.tipo==='montante').sort((a,b)=>a.x-b.x);const old=hnEspaciosActuales.slice();const lim=[hnModuloActual.espesor];mont.forEach(m=>lim.push(m.x-m.espesor/2,m.x+m.espesor/2));lim.push(hnModuloActual.ancho-hnModuloActual.espesor);const nuevos=[];for(let i=0;i+1<lim.length;i+=2){if(lim[i+1]-lim[i]<=10)continue;const o=old.find(s=>Math.abs(s.xMin-lim[i])<5&&Math.abs(s.xMax-lim[i+1])<5);nuevos.push({spaceId:o?.spaceId||hnId('space'),moduleId:hnModuloActual.moduleId,xMin:lim[i],xMax:lim[i+1],yMin:hnModuloActual.espesor,yMax:hnModuloActual.alto-hnModuloActual.espesor,profundidad:hnModuloActual.profundidad-hnModuloActual.fondo});}hnEspaciosActuales=nuevos;hnElementosActuales.filter(e=>e.tipo==='repisa').forEach(r=>{const s=hnEspaciosActuales.find(x=>r.x>=x.xMin&&r.x<=x.xMax)||hnEspaciosActuales[0];if(s){r.spaceId=s.spaceId;r.width=s.xMax-s.xMin;r.x=(s.xMin+s.xMax)/2;r.profundidad=s.profundidad;}});recalcularTodosLosCajones();}
function destinoActual(){if(hnSeleccionActual?.tipo==='sector')return{sector:hnSectoresActuales.find(s=>s.sectorId===hnSeleccionActual.objeto.sectorId)};if(hnSeleccionActual?.tipo==='espacio')return{space:hnEspaciosActuales.find(s=>s.spaceId===hnSeleccionActual.objeto.spaceId)};if(hnSeleccionActual?.tipo==='repisa')return{space:hnEspaciosActuales.find(s=>s.spaceId===hnSeleccionActual.objeto.spaceId)};if(hnSeleccionActual?.tipo==='cajon')return{sector:hnSectoresActuales.find(s=>s.sectorId===hnSeleccionActual.objeto.sectorId),space:hnEspaciosActuales.find(s=>s.spaceId===hnSeleccionActual.objeto.spaceId)};return{space:hnEspaciosActuales[0]};}
function agregarRepisaParametricaPrompt(){const d=destinoActual(),s=d.space||d.sector&&hnEspaciosActuales.find(x=>x.spaceId===d.sector.spaceId);if(!s)return;const q=parseInt(prompt('¿Cuántas repisas deseas agregar?','1'));if(!Number.isFinite(q)||q<=0)return;const y0=s.yMin,y1=s.yMax,sep=(y1-y0)/(q+1);for(let i=1;i<=q;i++){const y=y0+sep*i;const id=hnId('rep');hnElementosActuales.push({pieceId:id,moduleId:hnModuloActual.moduleId,spaceId:s.spaceId,tipo:'repisa',width:s.xMax-s.xMin,espesor:hnModuloActual.espesor,profundidad:s.profundidad,x:(s.xMin+s.xMax)/2,y,z:s.profundidad/2,material:'Blanco'});}recalcularSectores();recalcularTodosLosCajones();reconstruirEscena3DParametrica();actualizarSidebarEspacios();}
function agregarCajonParametricoPrompt(){const d=destinoActual();let sector=d.sector||null,space=d.space||(sector&&hnEspaciosActuales.find(s=>s.spaceId===sector.spaceId))||hnEspaciosActuales[0];if(!space)return;const q=parseInt(prompt(sector?`¿Cuántos cajones irán ÚNICAMENTE en el sector seleccionado?`:'¿Cuántos cajones deseas crear en el espacio seleccionado?','3'));if(!Number.isFinite(q)||q<=0)return;if(sector)generarConjuntoCajonesEnSector(sector,q);else generarConjuntoCajonesEnEspacio(space,q);hnSeleccionActual=sector?{tipo:'sector',objeto:sector}:hnSeleccionActual;reconstruirEscena3DParametrica();actualizarSidebarEspacios();if(sector)mostrarPropiedadesSector(sector);}
function eliminarGrupoCajones({sectorId=null,spaceId=null}={}){hnCajonesActuales=hnCajonesActuales.filter(c=>sectorId?c.sectorId!==sectorId: c.spaceId!==spaceId);}
function crearPiezasCajon(region,cantidad){const aw=region.xMax-region.xMin,ah=region.yMax-region.yMin,p=region.profundidad,T=hnModuloActual.espesor,gap=10;const usableH=ah-(cantidad+1)*gap;if(aw<=30||usableH<=20)return;const each=usableH/cantidad;for(let i=0;i<cantidad;i++){const drawerId=hnId('drw'),y0=region.yMin+gap+i*(each+gap),frontH=Math.max(10,each-4),latH=Math.max(8,each-30),latD=Math.max(30,p-40),backW=Math.max(10,aw-26-2*T);const piezas=[];const add=(tipo,a,h,d,x,y,z)=>piezas.push({pieceId:hnId('p'),drawerId,sectorId:region.sectorId||null,spaceId:region.spaceId,moduleId:hnModuloActual.moduleId,tipo,ancho:a,alto:h,profundidad:d,espesor:T,x,y,z});add('cajon_frente',Math.max(10,aw-4),frontH,T,(region.xMin+region.xMax)/2,y0+frontH/2,p-T/2);add('cajon_lateral_izq',T,latH,latD,region.xMin+T/2+10,y0+frontH/2,latD/2+20);add('cajon_lateral_der',T,latH,latD,region.xMax-T/2-10,y0+frontH/2,latD/2+20);add('cajon_trasera',backW,latH,T,(region.xMin+region.xMax)/2,y0+frontH/2,T/2+10);add('cajon_fondo',backW,Math.max(1,hnModuloActual.fondo),Math.max(10,latD-T),(region.xMin+region.xMax)/2,y0+hnModuloActual.fondo/2+5,(latD-T)/2+20);hnCajonesActuales.push({drawerId,sectorId:region.sectorId||null,spaceId:region.spaceId,moduleId:hnModuloActual.moduleId,cantidadEnGrupo:cantidad,piezas});}}
function generarConjuntoCajonesEnSector(sector,cantidad){eliminarGrupoCajones({sectorId:sector.sectorId});crearPiezasCajon(sector,cantidad);}
function generarConjuntoCajonesEnEspacio(espacio,cantidad){eliminarGrupoCajones({spaceId:espacio.spaceId});crearPiezasCajon(espacio,cantidad);}
function recalcularTodosLosCajones(){const grupos=[];hnCajonesActuales.forEach(c=>{let g=grupos.find(x=>(c.sectorId&&x.sectorId===c.sectorId)||(!c.sectorId&&!x.sectorId&&x.spaceId===c.spaceId));if(!g)grupos.push({sectorId:c.sectorId||null,spaceId:c.spaceId,cantidad:0});});grupos.forEach(g=>{g.cantidad=hnCajonesActuales.filter(c=>c.sectorId===g.sectorId&&c.spaceId===g.spaceId).length;});hnCajonesActuales=[];grupos.forEach(g=>{const s=g.sectorId?hnSectoresActuales.find(x=>x.sectorId===g.sectorId):hnEspaciosActuales.find(x=>x.spaceId===g.spaceId);if(s)crearPiezasCajon(s,Math.max(1,g.cantidad));});}

function actualizarSidebarEspacios(){const c=document.getElementById('hn-lista-espacios-sidebar');if(!c)return;c.innerHTML='';hnEspaciosActuales.forEach((s,i)=>{const div=document.createElement('div');div.className='hn-tool-item hn-space-card'+(hnSeleccionActual?.tipo==='espacio'&&hnSeleccionActual.objeto.spaceId===s.spaceId?' selected':'');div.onclick=()=>seleccionarEspacioPorId(s.spaceId);const secs=hnSectoresActuales.filter(x=>x.spaceId===s.spaceId);div.innerHTML=`<div style="display:flex;justify-content:space-between;gap:6px"><strong>Espacio #${i+1}</strong><span class="hn-note">${hnRound(s.xMax-s.xMin)} × ${hnRound(s.yMax-s.yMin)} mm</span></div><div style="font-size:.7rem;color:#6b7280">${secs.length} sector(es)</div>`;const list=document.createElement('div');list.className='hn-sector-list';secs.forEach((sec,j)=>{const item=document.createElement('div');item.className='hn-sector-item'+(hnSeleccionActual?.tipo==='sector'&&hnSeleccionActual.objeto.sectorId===sec.sectorId?' selected':'');item.onclick=e=>{e.stopPropagation();seleccionarSectorPorId(sec.sectorId);};item.innerHTML=`<span>Sector ${j+1}</span><span>${hnRound(sec.xMax-sec.xMin)} × ${hnRound(sec.yMax-sec.yMin)} mm</span>`;list.appendChild(item);});div.appendChild(list);c.appendChild(div);});}
function onHNDesignerClick(event){const c=document.getElementById('hn-viewport-3d');if(!c||!hnCamera||!hnScene)return;const r=c.getBoundingClientRect();hnMouse.x=((event.clientX-r.left)/r.width)*2-1;hnMouse.y=-((event.clientY-r.top)/r.height)*2+1;hnRaycaster.setFromCamera(hnMouse,hnCamera);const meshes=[];hnScene.traverse(o=>{if(o.isMesh&&o.userData?.isParametric&&o.userData.tipo!=='estructura')meshes.push(o);});const hits=hnRaycaster.intersectObjects(meshes,false);if(!hits.length){restaurarPanelDerechoMaestro();return;}const drawerHit=hits.find(h=>h.object.userData?.drawerId);if(drawerHit){const u=drawerHit.object.userData;seleccionarPiezaCajonPorId(u.drawerId,u.elementoData.pieceId);return;}const sectorHit=hits.find(h=>h.object.userData?.tipo==='sector');if(sectorHit){seleccionarSectorPorId(sectorHit.object.userData.sectorData.sectorId);return;}const elemHit=hits.find(h=>h.object.userData?.elementoData);if(elemHit)seleccionarElementoPorId(elemHit.object.userData.elementoData.pieceId);}
function seleccionarSectorPorId(id){const s=hnSectoresActuales.find(x=>x.sectorId===id);if(!s)return;hnSeleccionActual={tipo:'sector',objeto:s};reconstruirEscena3DParametrica();actualizarSidebarEspacios();mostrarPropiedadesSector(s);}
function seleccionarElementoPorId(id){const e=hnElementosActuales.find(x=>x.pieceId===id);if(!e)return;hnSeleccionActual={tipo:e.tipo,objeto:e};reconstruirEscena3DParametrica();actualizarSidebarEspacios();e.tipo==='montante'?mostrarPropiedadesMontante(e):mostrarPropiedadesRepisa(e);}
function seleccionarPiezaCajonPorId(did,pid){const c=hnCajonesActuales.find(x=>x.drawerId===did),p=c?.piezas.find(x=>x.pieceId===pid);if(!c||!p)return;hnSeleccionActual={tipo:'cajon',objeto:p,drawerId:did};reconstruirEscena3DParametrica();mostrarPropiedadesPiezaCajon(c,p);}
function seleccionarEspacioPorId(id){const s=hnEspaciosActuales.find(x=>x.spaceId===id);if(!s)return;hnSeleccionActual={tipo:'espacio',objeto:s};reconstruirEscena3DParametrica();actualizarSidebarEspacios();mostrarPropiedadesEspacio(s);}
function basePanel(title,badge,body){document.getElementById('hn-prop-title-text').innerText=title;const b=document.getElementById('hn-selected-badge');b.innerText=badge;b.style.background='#dcfce7';b.style.color='#166534';document.getElementById('hn-properties-content-container').innerHTML=body;}
function mostrarPropiedadesSector(s){const w=s.xMax-s.xMin,h=s.yMax-s.yMin;const drawers=hnCajonesActuales.filter(c=>c.sectorId===s.sectorId).length;basePanel('SECTOR SELECCIONADO','Ámbar',`<div class="hn-prop-row"><label>ID del Sector</label><input readonly value="${s.sectorId}"></div><div class="hn-prop-row"><label>Espacio padre</label><input readonly value="${s.spaceId}"></div><div class="hn-prop-row"><label>Ancho útil (mm)</label><input readonly value="${hnRound(w)}"></div><div class="hn-prop-row"><label>Alto útil (mm)</label><input readonly value="${hnRound(h)}"></div><div class="hn-prop-row"><label>Rango Y (mm)</label><input readonly value="${hnRound(s.yMin)} - ${hnRound(s.yMax)}"></div><div class="hn-info">Los cajones agregados desde este sector se generan únicamente dentro de este rectángulo.</div><div class="hn-properties-divider"></div><button class="hn-action-btn hn-action-green" onclick="agregarRepisaParametricaPrompt()">+ Agregar Repisa</button><button class="hn-action-btn hn-action-amber" onclick="agregarCajonParametricoPrompt()">+ Agregar Cajón en este Sector</button><button class="hn-action-btn hn-action-gray" onclick="restaurarPanelDerechoMaestro()">Deseleccionar Sector</button>${drawers?`<div class="hn-info">${drawers} cajón(es) dentro de este sector.</div>`:''}`);}
function mostrarPropiedadesEspacio(s){basePanel('ESPACIO INTERNO','Espacio',`<div class="hn-prop-row"><label>ID</label><input readonly value="${s.spaceId}"></div><div class="hn-prop-row"><label>Ancho útil (mm)</label><input readonly value="${hnRound(s.xMax-s.xMin)}"></div><div class="hn-prop-row"><label>Alto útil (mm)</label><input readonly value="${hnRound(s.yMax-s.yMin)}"></div><button class="hn-action-btn hn-action-green" onclick="agregarRepisaParametricaPrompt()">+ Agregar Repisa</button><button class="hn-action-btn hn-action-amber" onclick="agregarCajonParametricoPrompt()">+ Agregar Cajón</button><button class="hn-action-btn hn-action-gray" onclick="restaurarPanelDerechoMaestro()">Volver a Dimensiones Maestras</button>`);}
function mostrarPropiedadesMontante(e){basePanel('MONTANTE VERTICAL','Seleccionado',`<div class="hn-prop-row"><label>ID</label><input readonly value="${e.pieceId}"></div><div class="hn-prop-row"><label>Posición X (mm)</label><input type="number" value="${hnRound(e.x)}" oninput="actualizarPosicionMontanteManual('${e.pieceId}',this.value)"></div><div class="hn-prop-row"><label>Espesor (mm)</label><input readonly value="${e.espesor}"></div><button class="hn-action-btn hn-action-red" onclick="eliminarElementoParametrico('${e.pieceId}')">Eliminar Montante</button><button class="hn-action-btn hn-action-gray" onclick="restaurarPanelDerechoMaestro()">Volver</button>`);}
function mostrarPropiedadesRepisa(e){const s=hnEspaciosActuales.find(x=>x.spaceId===e.spaceId);basePanel('REPISA','Seleccionado',`<div class="hn-prop-row"><label>ID</label><input readonly value="${e.pieceId}"></div><div class="hn-prop-row"><label>Posición Y (mm)</label><input type="number" value="${hnRound(e.y)}" oninput="actualizarPosicionRepisaManual('${e.pieceId}',this.value)"></div><div class="hn-prop-row"><label>Ancho (mm)</label><input readonly value="${hnRound(e.width)}"></div><div class="hn-info">Rango: ${hnRound(s?.yMin||0)} - ${hnRound(s?.yMax||0)} mm</div><button class="hn-action-btn hn-action-red" onclick="eliminarElementoParametrico('${e.pieceId}')">Eliminar Repisa</button><button class="hn-action-btn hn-action-gray" onclick="restaurarPanelDerechoMaestro()">Volver</button>`);}
function mostrarPropiedadesPiezaCajon(c,p){basePanel('PIEZA DE CAJÓN','Cajón',`<div class="hn-prop-row"><label>ID pieza</label><input readonly value="${p.pieceId}"></div><div class="hn-prop-row"><label>ID cajón</label><input readonly value="${p.drawerId}"></div><div class="hn-prop-row"><label>Sector</label><input readonly value="${p.sectorId||'Espacio completo'}"></div><div class="hn-prop-row"><label>Tipo</label><input readonly value="${p.tipo}"></div><div class="hn-prop-row"><label>Dimensiones (mm)</label><input readonly value="${hnRound(p.ancho)} × ${hnRound(p.alto)} × ${hnRound(p.profundidad)}"></div><button class="hn-action-btn hn-action-red" onclick="eliminarCajonParametrico('${c.drawerId}')">Eliminar Cajón Completo</button><button class="hn-action-btn hn-action-gray" onclick="restaurarPanelDerechoMaestro()">Volver</button>`);}
function actualizarPosicionMontanteManual(id,v){const n=parseFloat(v),e=hnElementosActuales.find(x=>x.pieceId===id);if(!e||!Number.isFinite(n))return;if(n>hnModuloActual.espesor+10&&n<hnModuloActual.ancho-hnModuloActual.espesor-10){e.x=n;recalcularEspaciosYElementosPorMontante();recalcularSectores();recalcularTodosLosCajones();reconstruirEscena3DParametrica();actualizarSidebarEspacios();mostrarPropiedadesMontante(e);}}
function actualizarPosicionRepisaManual(id,v){const n=parseFloat(v),e=hnElementosActuales.find(x=>x.pieceId===id),s=e&&hnEspaciosActuales.find(x=>x.spaceId===e.spaceId);if(!e||!s||!Number.isFinite(n))return;if(n>=s.yMin+e.espesor/2&&n<=s.yMax-e.espesor/2){e.y=n;recalcularSectores();recalcularTodosLosCajones();reconstruirEscena3DParametrica();actualizarSidebarEspacios();mostrarPropiedadesRepisa(e);}}
function eliminarElementoParametrico(id){const e=hnElementosActuales.find(x=>x.pieceId===id);hnElementosActuales=hnElementosActuales.filter(x=>x.pieceId!==id);if(e?.tipo==='montante')recalcularEspaciosYElementosPorMontante();recalcularSectores();recalcularTodosLosCajones();restaurarPanelDerechoMaestro();actualizarSidebarEspacios();}
function eliminarCajonParametrico(id){hnCajonesActuales=hnCajonesActuales.filter(c=>c.drawerId!==id);restaurarPanelDerechoMaestro();reconstruirEscena3DParametrica();actualizarSidebarEspacios();}
function restaurarPanelDerechoMaestro(rebuild=true){hnSeleccionActual=null;if(rebuild)reconstruirEscena3DParametrica();actualizarSidebarEspacios();basePanel('DIMENSIONES MAESTRAS','Módulo',`<div class="hn-prop-row"><label>Ancho (mm)</label><input type="number" value="${hnModuloActual.ancho}" id="hn-master-ancho" oninput="actualizarDimensionesMaestrasDebounced()"></div><div class="hn-prop-row"><label>Alto (mm)</label><input type="number" value="${hnModuloActual.alto}" id="hn-master-alto" oninput="actualizarDimensionesMaestrasDebounced()"></div><div class="hn-prop-row"><label>Profundidad (mm)</label><input type="number" value="${hnModuloActual.profundidad}" id="hn-master-prof" oninput="actualizarDimensionesMaestrasDebounced()"></div><div class="hn-prop-row"><label>Espesor estructural (mm)</label><input type="number" value="${hnModuloActual.espesor}" id="hn-master-espesor" oninput="actualizarDimensionesMaestrasDebounced()"></div><div class="hn-prop-row"><label>Fondo (mm)</label><input type="number" value="${hnModuloActual.fondo}" id="hn-master-fondo" oninput="actualizarDimensionesMaestrasDebounced()"></div><div class="hn-properties-divider"></div><div class="hn-info">Modifica las dimensiones maestras para recalcular estructura, espacios, sectores y elementos automáticamente.</div>`);}
document.addEventListener('keydown',e=>{if(e.key==='Escape')cerrarHNDesigner();});
abrirHNDesigner();
